Repository Infinite-Loop-Club/club-site, pull requests merged in 2021-03, with the labels that each got.

#10 Form enhancements 1
  package-lock.json
  src/images/female-1.png
  src/images/female-2.png
  src/images/female-3.png
  src/images/male-1.png
  src/images/male-2.png
  src/images/male-3.png
  src/pages/register.js
Labels: enhancement

#19 improved btn - added `<Link>` and `<a>` support & bug fixes
  src/components/Button.js
  src/pages/home/Hero.js
  src/pages/home/Register.js
Labels: enhancement

#22 Form enhancements 2
  package-lock.json
  package.json
  src/Router.js
  src/constants/theme.js
  src/pages/RegistrationForm/register.js
  src/pages/RegistrationForm/validationSchema.js
  src/pages/index.js
  src/pages/register.js
Labels: enhancement

#24 small fixes patch 2
  README.md
  src/App.js
  src/Routers.js
  src/components/Card.js
  src/index.js
  src/pages/home/CTA.js
  src/pages/home/Hero.js
  src/pages/home/Members.js
  src/pages/home/index.js
Labels: enhancement

#25 Small fixes and tweaks
  README.md
  package-lock.json
  package.json
  src/components/BackgroundStripes.js
  src/components/Footer.js
  src/components/Heading.js
  src/components/Nav.js
  src/components/index.js
  src/images/dev-github.svg
  src/images/index.js
  src/images/interview.svg
  src/images/logo-colored.svg
  src/images/logo-white.png
  src/images/meeting.svg
  src/images/team.svg
  src/pages/about.js
  src/pages/home/CTA.js
  src/pages/home/Features.js
  src/pages/home/Hero.js
  src/pages/home/Members.js
  src/pages/index.js
  src/pages/post/Card.js
  src/pages/post/IndividualPost.js
  src/pages/post/Post.jsx
  src/pages/post/index.js
  src/pages/register/index.js
  src/pages/register/validationSchema.js
Labels: enhancement

#29 Integrated registation form API
  package-lock.json
  package.json
  public/index.html
  src/Routers.js
  src/constants/theme.js
  src/images/index.js
  src/images/logo-translucent.png
  src/pages/register/index.js
  src/pages/register/membership-card.js
Labels: feature

#30 About us page and card improved
  package-lock.json
  package.json
  src/Routers.js
  src/constants/theme.js
  src/images/index.js
  src/images/man1.png
  src/pages/about.js
  src/pages/about/AboutCard.js
  src/pages/about/TeamDetails.js
  src/pages/about/index.js
Labels: enhancement

#34 added jsconfig and absolute imports
  jsconfig.json
  package-lock.json
  src/App.js
  src/Routers.js
  src/components/Button.js
  src/components/Card.js
  src/components/Footer.js
  src/components/Heading.js
  src/components/Loader.js
  src/index.js
  src/pages/about/AboutCard.js
  src/pages/about/TeamDetails.js
  src/pages/about/index.js
  src/pages/home/CTA.js
  src/pages/home/Features.js
  src/pages/home/Hero.js
  src/pages/home/Members.js
  src/pages/post/IndividualPost.js
  src/pages/post/Share.js
  src/pages/post/index.js
  src/pages/register/index.js
  src/pages/register/membership-card.js
Labels: enhancement, quality-fix

#38 Custom post page added
  src/Routers.js
  src/components/LoaderContainer.js
  src/components/index.js
  src/pages/index.js
  src/pages/post/CustomPost.jsx
  src/pages/post/Share.js
  src/pages/post/index.js
Labels: enhancement

#41 Fixes krish 1
  src/components/Button.js
  src/index.js
  src/pages/register/index.js
  src/pages/register/membership-card.js
Labels: bug, enhancement, feature, quality-fix

#53 post view updated
  package-lock.json
  package.json
  src/App.js
  src/pages/post/Card.js
  src/pages/post/Content.jsx
  src/pages/post/CustomPost.js
  src/pages/post/IndividualPost.js
Labels: enhancement

#54 Fixes patch 4
  src/pages/about/AboutCard.js
  src/pages/about/TeamDetails.js
  src/pages/about/index.js
  src/pages/about/members.js
  src/pages/home/Hero.js
  src/pages/home/Members.js
  src/pages/register/membership-card.js
Labels: enhancement
