Repository Infinite-Loop-Club/club-site, pull requests merged in 2021-04, with the labels that each got.

#55 Fixed department and image bug
  public/images/female-1.png
  public/images/female-2.png
  public/images/female-3.png
  public/images/male-1.png
  public/images/male-2.png
  public/images/male-3.png
  src/images/index.js
  src/pages/register/index.js
  src/pages/register/validationSchema.js
Labels: bug

#62 Post election
  src/Routers.js
  src/components/Card.js
  src/components/Nav.js
  src/components/index.js
  src/images/benxene-without-name.png
  src/images/index.js
  src/pages/about/AboutCard.js
  src/pages/about/TeamContainer.js
  src/pages/about/TeamDetails.js
  src/pages/about/index.js
  src/pages/about/members.js
  src/pages/home/CTA.js
  src/pages/home/Members.js
  src/pages/home/index.js
  src/pages/index.js
  src/pages/register/index.js
Labels: enhancement

#64 Refactor patch 1
  src/components/BackgroundStripes.js
  src/components/Button.js
  src/components/Card.js
  src/components/Container.js
  src/components/Footer.js
  src/components/Nav.js
  src/components/index.js
  src/constants/avatars.js
  src/data/members.js
  src/data/nominees.js
  src/pages/about/AboutCard.js
  src/pages/about/TeamContainer.js
  src/pages/about/TeamDetails.js
  src/pages/about/index.js
  src/pages/home/CTA.js
  src/pages/home/FeatureItem.js
  src/pages/home/Features.js
  src/pages/home/Hero.js
  src/pages/home/Members.js
  src/pages/home/index.js
  src/pages/post/Content.js
  src/pages/post/CustomPost.js
  src/pages/post/IndividualPost.js
  src/pages/post/index.js
  src/pages/register/index.js
  src/pages/register/membership-card.js
  src/pages/voting/index.js
Labels: enhancement, quality-fix

#65 fixed card layout
  src/data/members.js
  src/pages/about/AboutCard.js
  src/pages/about/TeamContainer.js
  src/pages/about/index.js
Labels: enhancement
